name: pos_printer_helper
description: "A Flutter package that provides a unified interface for thermal printer operations across multiple POS device manufacturers."
version: 1.1.3
repository: 'https://github.com/abdalla19977/pos_printer'
topics : 
  - printing
  - thermal

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'
  

dependencies:
  flutter:
    sdk: flutter
  pigeon: 
  plugin_platform_interface: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  plugin:
    platforms:
      android:
        package: com.cashier.pos_printer
        pluginClass: PosPrinterPlugin

